/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visoes;

import DAO.PEDao;
import DAO.ProdutoDao;
import Entidades.Produtoestoque;
import Entidades.ProdutoestoqueId;
import Entidades.Produtos;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Murilo
 */
public class CadastroProduto extends javax.swing.JFrame {

    /**
     * Creates new form CadastroProduto
     */
    public CadastroProduto() {
        initComponents();
    }
    
    private void carregaProduto (Produtos produto) {
        edCodigo.setText(produto.getCodigo().toString());
        edDesc.setText(produto.getDescricao());
        edMarca.setText(produto.getMarca());        
    }

    private void limpaTable() {
        DefaultTableModel model = (DefaultTableModel) gdProdutos.getModel();
        for (int i = model.getRowCount() - 1; i >= 0; i--) {
            model.removeRow(i);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PesquisaProdutos = new javax.swing.JDialog();
        label_descConta = new javax.swing.JLabel();
        edDescP = new javax.swing.JTextField();
        btPesquisa1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gdProdutos = new javax.swing.JTable();
        btCarregar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        edMarca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edCodigo = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        edDesc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();

        label_descConta.setText("Marca");

        edDescP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                edDescPFocusLost(evt);
            }
        });
        edDescP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edDescPActionPerformed(evt);
            }
        });
        edDescP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edDescPKeyReleased(evt);
            }
        });

        btPesquisa1.setText("Pesquisar");
        btPesquisa1.setMargin(new java.awt.Insets(2, 1, 2, 1));
        btPesquisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisa1ActionPerformed(evt);
            }
        });

        gdProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descricao", "Marca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gdProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gdProdutosMouseClicked(evt);
            }
        });
        gdProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gdProdutosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gdProdutosKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(gdProdutos);

        btCarregar.setText("Carregar");
        btCarregar.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCarregarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PesquisaProdutosLayout = new javax.swing.GroupLayout(PesquisaProdutos.getContentPane());
        PesquisaProdutos.getContentPane().setLayout(PesquisaProdutosLayout);
        PesquisaProdutosLayout.setHorizontalGroup(
            PesquisaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesquisaProdutosLayout.createSequentialGroup()
                .addGroup(PesquisaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PesquisaProdutosLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PesquisaProdutosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PesquisaProdutosLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(label_descConta, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edDescP, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PesquisaProdutosLayout.setVerticalGroup(
            PesquisaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesquisaProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PesquisaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_descConta)
                    .addComponent(edDescP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisa1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(PesquisaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCarregar)
                    .addComponent(btCancelar))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manutenção de produtos");

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Marca:");

        jLabel2.setText("Código:");

        edCodigo.setEditable(false);

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Murilo\\Documents\\NetBeansProjects\\ProjetosPAA\\images.png")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setText("Descrição:");

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(edCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(edDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(edMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(edDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(btNovo))
                    .addComponent(jButton2))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Produtos produto = new Produtos();
        ProdutoDao produtoDao = new ProdutoDao();
        boolean retornoProd = false;
        if (edCodigo.getText().equals("")) {
            produto.setDescricao(edDesc.getText());
            produto.setMarca(edMarca.getText());

            retornoProd = produtoDao.InsertProdutos(produto);
        } else {
            boolean existe = produtoDao.existeNoBanco(Integer.parseInt(edCodigo.getText()));
            if (existe){
                produto.setCodigo(Integer.parseInt(edCodigo.getText()));
                produto.setDescricao(edDesc.getText());
                produto.setMarca(edMarca.getText());
                retornoProd = produtoDao.updateProdutos(produto);
            }
        }
        if (retornoProd == true) {
            JOptionPane.showMessageDialog(null, "Gravado com sucesso!");
            carregaProduto(produto);            
        } else {
            JOptionPane.showMessageDialog(null, "Erro!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        PesquisaProdutos.setSize(600, 450);
        PesquisaProdutos.setModal(true);
        PesquisaProdutos.setLocation(200, 100);
        PesquisaProdutos.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void edDescPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edDescPFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_edDescPFocusLost

    private void edDescPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edDescPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edDescPActionPerformed

    private void edDescPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edDescPKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_edDescPKeyReleased

    private void btPesquisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisa1ActionPerformed
        limpaTable();
        DefaultTableModel model = (DefaultTableModel) gdProdutos.getModel();
        ProdutoDao produtoDao = new ProdutoDao();
        List<Produtos> list = new ArrayList();

        if (edDescP.getText().equals("")) {
            try {
                list = produtoDao.pesqView();
            } catch (Exception ex) {
                Logger.getLogger(PesquisaProdutos.getName()).log(Level.SEVERE, null, ex);
                Login.log.info("Erro ao pesquisar produto(CadastroProduto): " + ex);
            }
        } else {
            try {
                list = produtoDao.pesquisaProdutos(edDescP.getText());
            } catch (Exception ex) {
                Logger.getLogger(PesquisaProdutos.getName()).log(Level.SEVERE, null, ex);
                Login.log.info("Erro ao pesquisar produto(CadastroProduto): " + ex);
            }
        }

        if (list.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Produto não localizado.", "Erro",
                JOptionPane.ERROR_MESSAGE);
            btCarregar.setEnabled(false);
        } else {
            String tabela[] = new String[]{"", "", ""};
            for (Produtos produto : list) {
                tabela[0] = String.valueOf(produto.getCodigo());
                tabela[1] = produto.getDescricao();
                tabela[2] = produto.getMarca();                
                model.addRow(tabela);
            }
            btCarregar.setEnabled(true);
            gdProdutos.setVisible(true);
        }
    }//GEN-LAST:event_btPesquisa1ActionPerformed

    private void gdProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gdProdutosMouseClicked
        if (evt.getClickCount() == 2) {
            if (gdProdutos.getSelectedRow() > -1) {
                edCodigo.setText(gdProdutos.getValueAt(gdProdutos.getSelectedRow(), 0).toString());
                edDesc.setText(gdProdutos.getValueAt(gdProdutos.getSelectedRow(), 1).toString());
                edMarca.setText(gdProdutos.getValueAt(gdProdutos.getSelectedRow(), 2).toString());            
                PesquisaProdutos.setVisible(false);
            }
        }
    }//GEN-LAST:event_gdProdutosMouseClicked

    private void gdProdutosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gdProdutosKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_gdProdutosKeyReleased

    private void gdProdutosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gdProdutosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_gdProdutosKeyTyped

    private void btCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCarregarActionPerformed
        //DefaultTableModel model = (DefaultTableModel) gdClientes.getModel();
        if (gdProdutos.getSelectedRow() > -1) {
            edCodigo.setText(gdProdutos.getValueAt(gdProdutos.getSelectedRow(), 0).toString());
            edDesc.setText(gdProdutos.getValueAt(gdProdutos.getSelectedRow(), 1).toString());
            edMarca.setText(gdProdutos.getValueAt(gdProdutos.getSelectedRow(), 2).toString());            
            PesquisaProdutos.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecione algum produto da lista.", "Erro",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btCarregarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        PesquisaProdutos.setVisible(false);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        edCodigo.setText("");
        edDesc.setText("");
        edMarca.setText("");
        edDesc.grabFocus();
    }//GEN-LAST:event_btNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog PesquisaProdutos;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btCarregar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisa1;
    private javax.swing.JTextField edCodigo;
    private javax.swing.JTextField edDesc;
    private javax.swing.JTextField edDescP;
    private javax.swing.JTextField edMarca;
    private javax.swing.JTable gdProdutos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_descConta;
    // End of variables declaration//GEN-END:variables
}
