/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visoes;

import Controle.Formatacao;
import Controle.MiscTools;
import DAO.PEDao;
import DAO.ProdutoDao;
import Entidades.Produtoestoque;
import Entidades.ProdutoestoqueId;
import Entidades.Produtos;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Murilo
 */
public class CadastroProdEst extends javax.swing.JFrame {

    /**
     * Creates new form CadastroProdEst
     */
    public CadastroProdEst() {
        initComponents();
    }
    
    private void limpaTable() {
        DefaultTableModel model = (DefaultTableModel) gdProdutos.getModel();
        for (int i = model.getRowCount() - 1; i >= 0; i--) {
            model.removeRow(i);
        }
    }
    
    private void limpaTablePE() {
        DefaultTableModel model = (DefaultTableModel) gdPe.getModel();
        for (int i = model.getRowCount() - 1; i >= 0; i--) {
            model.removeRow(i);
        }
    }
    
    private void carregaPE (Produtoestoque pe) {
        //edCodigo.setText(pe.getCodigo().toString());
        edCusto.setText(String.valueOf(pe.getCusto()));
        edvalVen.setText(String.valueOf(pe.getValorVenda()));
        edQtd.setText(String.valueOf(pe.getQtd()));
        edDt.setText(pe.getDtEntrada().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PesquisaProdutos = new javax.swing.JDialog();
        label_descConta = new javax.swing.JLabel();
        edDescP = new javax.swing.JTextField();
        btPesquisa1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gdProdutos = new javax.swing.JTable();
        btCarregar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        PesqPE = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        gdPe = new javax.swing.JTable();
        label_descConta1 = new javax.swing.JLabel();
        edProd = new javax.swing.JTextField();
        btPesqP = new javax.swing.JButton();
        btCarregarPro = new javax.swing.JButton();
        btCancelarPE = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        edProduto = new javax.swing.JTextField();
        btPesquisa = new javax.swing.JButton();
        edDescPro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        edCodigo = new javax.swing.JTextField();
        edDt = new javax.swing.JFormattedTextField();
        edCusto = new javax.swing.JFormattedTextField();
        edvalVen = new javax.swing.JFormattedTextField();
        edQtd = new javax.swing.JFormattedTextField();
        btPesquProEst = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        label_descConta.setText("Marca");

        edDescP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                edDescPFocusLost(evt);
            }
        });
        edDescP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edDescPActionPerformed(evt);
            }
        });
        edDescP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edDescPKeyReleased(evt);
            }
        });

        btPesquisa1.setText("Pesquisar");
        btPesquisa1.setMargin(new java.awt.Insets(2, 1, 2, 1));
        btPesquisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisa1ActionPerformed(evt);
            }
        });

        gdProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descricao", "Marca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gdProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gdProdutosMouseClicked(evt);
            }
        });
        gdProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gdProdutosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gdProdutosKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(gdProdutos);

        btCarregar.setText("Carregar");
        btCarregar.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCarregarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PesquisaProdutosLayout = new javax.swing.GroupLayout(PesquisaProdutos.getContentPane());
        PesquisaProdutos.getContentPane().setLayout(PesquisaProdutosLayout);
        PesquisaProdutosLayout.setHorizontalGroup(
            PesquisaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesquisaProdutosLayout.createSequentialGroup()
                .addGroup(PesquisaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PesquisaProdutosLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PesquisaProdutosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PesquisaProdutosLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(label_descConta, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edDescP, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PesquisaProdutosLayout.setVerticalGroup(
            PesquisaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesquisaProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PesquisaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_descConta)
                    .addComponent(edDescP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisa1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(PesquisaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCarregar)
                    .addComponent(btCancelar))
                .addContainerGap())
        );

        gdPe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Cod. estoque", "Descricao", "Custo", "Valor de venda", "Qtd", "Dt entrada", "Marca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gdPe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gdPeMouseClicked(evt);
            }
        });
        gdPe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gdPeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gdPeKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(gdPe);
        if (gdPe.getColumnModel().getColumnCount() > 0) {
            gdPe.getColumnModel().getColumn(0).setResizable(false);
            gdPe.getColumnModel().getColumn(0).setPreferredWidth(50);
            gdPe.getColumnModel().getColumn(1).setResizable(false);
            gdPe.getColumnModel().getColumn(1).setPreferredWidth(50);
            gdPe.getColumnModel().getColumn(2).setResizable(false);
            gdPe.getColumnModel().getColumn(2).setPreferredWidth(100);
            gdPe.getColumnModel().getColumn(3).setResizable(false);
            gdPe.getColumnModel().getColumn(3).setPreferredWidth(40);
            gdPe.getColumnModel().getColumn(4).setResizable(false);
            gdPe.getColumnModel().getColumn(4).setPreferredWidth(70);
            gdPe.getColumnModel().getColumn(5).setResizable(false);
            gdPe.getColumnModel().getColumn(5).setPreferredWidth(30);
            gdPe.getColumnModel().getColumn(6).setResizable(false);
            gdPe.getColumnModel().getColumn(6).setPreferredWidth(60);
            gdPe.getColumnModel().getColumn(7).setResizable(false);
            gdPe.getColumnModel().getColumn(7).setPreferredWidth(50);
        }

        label_descConta1.setText("Produto:");

        edProd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                edProdFocusLost(evt);
            }
        });
        edProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edProdActionPerformed(evt);
            }
        });
        edProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edProdKeyReleased(evt);
            }
        });

        btPesqP.setText("Pesquisar");
        btPesqP.setMargin(new java.awt.Insets(2, 1, 2, 1));
        btPesqP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesqPActionPerformed(evt);
            }
        });

        btCarregarPro.setText("Carregar");
        btCarregarPro.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btCarregarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCarregarProActionPerformed(evt);
            }
        });

        btCancelarPE.setText("Cancelar");
        btCancelarPE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarPEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PesqPELayout = new javax.swing.GroupLayout(PesqPE.getContentPane());
        PesqPE.getContentPane().setLayout(PesqPELayout);
        PesqPELayout.setHorizontalGroup(
            PesqPELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesqPELayout.createSequentialGroup()
                .addGroup(PesqPELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PesqPELayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCarregarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancelarPE, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PesqPELayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PesqPELayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(label_descConta1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edProd, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPesqP, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PesqPELayout.setVerticalGroup(
            PesqPELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesqPELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PesqPELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_descConta1)
                    .addComponent(edProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesqP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(PesqPELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCarregarPro)
                    .addComponent(btCancelarPE))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manutenção de produtos do estoque");

        jPanel1.setMinimumSize(new java.awt.Dimension(380, 260));
        jPanel1.setName("Manutenção de clientes"); // NOI18N

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        jLabel2.setText("Produto:");

        jLabel3.setText("Custo:");

        jLabel4.setText("Valor venda:");

        jLabel5.setText("Qtd:");

        jLabel6.setText("Data entrada:");

        edProduto.setEditable(false);
        edProduto.setName("edProduto"); // NOI18N
        edProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                edProdutoFocusLost(evt);
            }
        });
        edProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edProdutoActionPerformed(evt);
            }
        });
        edProduto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                edProdutoPropertyChange(evt);
            }
        });
        edProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edProdutoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edProdutoKeyTyped(evt);
            }
        });
        edProduto.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                edProdutoVetoableChange(evt);
            }
        });

        btPesquisa.setIcon(new javax.swing.ImageIcon("C:\\Users\\Murilo\\Documents\\NetBeansProjects\\ProjetosPAA\\images.png")); // NOI18N
        btPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaActionPerformed(evt);
            }
        });

        edDescPro.setEditable(false);
        edDescPro.setName("edCodigo"); // NOI18N
        edDescPro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                edDescProFocusLost(evt);
            }
        });
        edDescPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edDescProActionPerformed(evt);
            }
        });
        edDescPro.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                edDescProPropertyChange(evt);
            }
        });
        edDescPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edDescProKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edDescProKeyTyped(evt);
            }
        });
        edDescPro.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                edDescProVetoableChange(evt);
            }
        });

        jLabel7.setText("Código:");

        edCodigo.setName("edProduto"); // NOI18N
        edCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                edCodigoFocusLost(evt);
            }
        });
        edCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edCodigoActionPerformed(evt);
            }
        });
        edCodigo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                edCodigoPropertyChange(evt);
            }
        });
        edCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edCodigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edCodigoKeyTyped(evt);
            }
        });
        edCodigo.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                edCodigoVetoableChange(evt);
            }
        });

        edDt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));

        edCusto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        edvalVen.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        edQtd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        btPesquProEst.setIcon(new javax.swing.ImageIcon("C:\\Users\\Murilo\\Documents\\NetBeansProjects\\ProjetosPAA\\images.png")); // NOI18N
        btPesquProEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquProEstActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(74, 74, 74)
                                    .addComponent(jLabel3))
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(edCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btPesquProEst, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(edDescPro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(edQtd, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(edvalVen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(edDt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(edCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(btPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edDescPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btPesquProEst, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(edCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edvalVen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edDt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btNovo)
                    .addComponent(btSair))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Produtoestoque pe = new Produtoestoque();        
        ProdutoestoqueId peid = new ProdutoestoqueId();
        PEDao peDao = new PEDao();
        boolean retorno = false;        
        boolean existe = peDao.existeNoBanco(Integer.parseInt(edProduto.getText()), Integer.parseInt(edCodigo.getText()));
        peid.setProdutosCodigo(Integer.parseInt(edProduto.getText()));
        peid.setCodigoEstoque(Integer.parseInt(edCodigo.getText()));
        pe.setId(peid);
        pe.setCusto(Double.parseDouble(edCusto.getText().replace(',', '.')));
        pe.setValorVenda(Double.parseDouble(edvalVen.getText().replace(',', '.')));
        pe.setQtd(Integer.parseInt(edQtd.getText()));
                
        pe.setDtEntrada(edDt.getText());        
        
        if (existe) {
            retorno = peDao.updatePE(pe);
        } else {
            retorno = peDao.InsertPE(pe);
        }                
        if (retorno == true) {
            JOptionPane.showMessageDialog(null, "Gravado com sucesso!");
            carregaPE(pe);
        } else {
            JOptionPane.showMessageDialog(null, "Erro!");
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        PEDao pedao = new PEDao();
        if (edProduto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Carregue o código do produto.");
        } else {
            int novo = pedao.novo(Integer.parseInt(edProduto.getText()));
            edCodigo.setText(Integer.toString(novo));
        }
        edCusto.setText("");
        edvalVen.setText("");
        edQtd.setText("");
        edDt.setText("");
        edCusto.grabFocus();
    }//GEN-LAST:event_btNovoActionPerformed

    private void edProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edProdutoFocusLost
        
    }//GEN-LAST:event_edProdutoFocusLost

    private void edProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edProdutoActionPerformed

    private void edProdutoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_edProdutoPropertyChange

    }//GEN-LAST:event_edProdutoPropertyChange

    private void edProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edProdutoKeyReleased

    }//GEN-LAST:event_edProdutoKeyReleased

    private void edProdutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edProdutoKeyTyped

    }//GEN-LAST:event_edProdutoKeyTyped

    private void edProdutoVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_edProdutoVetoableChange

    }//GEN-LAST:event_edProdutoVetoableChange

    private void btPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaActionPerformed
        PesquisaProdutos.setSize(600, 450);
        PesquisaProdutos.setModal(true);
        PesquisaProdutos.setLocation(200, 100);
        PesquisaProdutos.setVisible(true);
    }//GEN-LAST:event_btPesquisaActionPerformed

    private void edDescProFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edDescProFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_edDescProFocusLost

    private void edDescProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edDescProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edDescProActionPerformed

    private void edDescProPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_edDescProPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_edDescProPropertyChange

    private void edDescProKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edDescProKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_edDescProKeyReleased

    private void edDescProKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edDescProKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_edDescProKeyTyped

    private void edDescProVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_edDescProVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_edDescProVetoableChange

    private void edCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edCodigoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_edCodigoFocusLost

    private void edCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edCodigoActionPerformed

    private void edCodigoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_edCodigoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_edCodigoPropertyChange

    private void edCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edCodigoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_edCodigoKeyReleased

    private void edCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edCodigoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_edCodigoKeyTyped

    private void edCodigoVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_edCodigoVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_edCodigoVetoableChange

    private void edDescPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edDescPFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_edDescPFocusLost

    private void edDescPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edDescPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edDescPActionPerformed

    private void edDescPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edDescPKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_edDescPKeyReleased

    private void btPesquisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisa1ActionPerformed
        limpaTable();
        DefaultTableModel model = (DefaultTableModel) gdProdutos.getModel();
        ProdutoDao produtoDao = new ProdutoDao();
        List<Produtos> list = new ArrayList();

        if (edDescP.getText().equals("")) {
            try {
                list = produtoDao.encontrarTudo();
            } catch (Exception ex) {
                Logger.getLogger(PesquisaProdutos.getName()).log(Level.SEVERE, null, ex);
                Login.log.info("Erro ao pesquisar produtos(CadastroProdEst): " + ex);
            }
        } else {
            try {
                list = produtoDao.pesquisaProdutos(edDescP.getText());
            } catch (Exception ex) {
                Logger.getLogger(PesquisaProdutos.getName()).log(Level.SEVERE, null, ex);
                Login.log.info("Erro ao pesquisar produtos(CadastroProdEst): " + ex);
            }
        }

        if (list.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Produto não localizado.", "Erro",
                JOptionPane.ERROR_MESSAGE);
            btCarregar.setEnabled(false);
        } else {
            String tabela[] = new String[]{"", "", ""};
            for (Produtos produto : list) {
                tabela[0] = String.valueOf(produto.getCodigo());
                tabela[1] = produto.getDescricao();
                tabela[2] = produto.getMarca();
                model.addRow(tabela);
            }
            btCarregar.setEnabled(true);
            gdProdutos.setVisible(true);
        }
    }//GEN-LAST:event_btPesquisa1ActionPerformed

    private void gdProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gdProdutosMouseClicked
        if (evt.getClickCount() == 2) {
            if (gdProdutos.getSelectedRow() > -1) {
                edProduto.setText(gdProdutos.getValueAt(gdProdutos.getSelectedRow(), 0).toString());
                edDescPro.setText(gdProdutos.getValueAt(gdProdutos.getSelectedRow(), 1).toString());                
                PesquisaProdutos.setVisible(false);
            }
        }
    }//GEN-LAST:event_gdProdutosMouseClicked

    private void gdProdutosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gdProdutosKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_gdProdutosKeyReleased

    private void gdProdutosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gdProdutosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_gdProdutosKeyTyped

    private void btCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCarregarActionPerformed
        //DefaultTableModel model = (DefaultTableModel) gdClientes.getModel();
        if (gdProdutos.getSelectedRow() > -1) {
            edProduto.setText(gdProdutos.getValueAt(gdProdutos.getSelectedRow(), 0).toString());
            edDescPro.setText(gdProdutos.getValueAt(gdProdutos.getSelectedRow(), 1).toString());                
            PesquisaProdutos.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecione algum produto da lista.", "Erro",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btCarregarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        PesquisaProdutos.setVisible(false);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btPesquProEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquProEstActionPerformed
        PesqPE.setSize(600, 450);
        PesqPE.setModal(true);
        PesqPE.setLocation(200, 100);
        PesqPE.setVisible(true);
    }//GEN-LAST:event_btPesquProEstActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btSairActionPerformed

    private void gdPeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gdPeMouseClicked
        if (evt.getClickCount() == 2) {
            if (gdPe.getSelectedRow() > -1) {
                edProduto.setText(gdPe.getValueAt(gdPe.getSelectedRow(), 0).toString());
                edCodigo.setText(gdPe.getValueAt(gdPe.getSelectedRow(), 1).toString());
                edDescPro.setText(gdPe.getValueAt(gdPe.getSelectedRow(), 2).toString());                        
                edCusto.setText(gdPe.getValueAt(gdPe.getSelectedRow(), 3).toString());
                edvalVen.setText(gdPe.getValueAt(gdPe.getSelectedRow(),4).toString());
                edQtd.setText(gdPe.getValueAt(gdPe.getSelectedRow(), 5).toString());
                edDt.setText(gdPe.getValueAt(gdPe.getSelectedRow(), 6).toString());
                PesqPE.setVisible(false);
            } else {
               JOptionPane.showMessageDialog(this, "Por favor, selecione algum produtos da lista.", "Erro",
               JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_gdPeMouseClicked

    private void gdPeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gdPeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_gdPeKeyReleased

    private void gdPeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gdPeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_gdPeKeyTyped

    private void edProdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edProdFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_edProdFocusLost

    private void edProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edProdActionPerformed

    private void edProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edProdKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_edProdKeyReleased

    private void btPesqPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesqPActionPerformed
        limpaTablePE();
        DefaultTableModel model = (DefaultTableModel) gdPe.getModel();
        ProdutoDao produtoDao = new ProdutoDao();
        PEDao peDao = new PEDao();
        List<Produtoestoque> list = new ArrayList();

        if (edProd.getText().equals("")) {
            try {
                list = peDao.pesqView();
            } catch (Exception ex) {
                Logger.getLogger(PesqPE.getName()).log(Level.SEVERE, null, ex);
                Login.log.info("Erro ao pesquisar produtoEstoque(CadastroProdEst): " + ex);
            }
        } else {
            try {
                list = peDao.pesqDesc(edProd.getText());
            } catch (Exception ex) {
                Logger.getLogger(PesqPE.getName()).log(Level.SEVERE, null, ex);
                Login.log.info("Erro ao pesquisar produtoEstoque(CadastroProdEst): " + ex);
            }
        }

        if (list.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Produto não localizado.", "Erro",
                JOptionPane.ERROR_MESSAGE);
            btCarregar.setEnabled(false);
        } else {
            String tabela[] = new String[]{"","","","","","","",""};
            for (Produtoestoque pe : list) {                                                      
                tabela[0] = String.valueOf(pe.getProdutos().getCodigo());
                tabela[1] = String.valueOf(pe.getId().getCodigoEstoque());
                tabela[2] = pe.getProdutos().getDescricao();
                tabela[3] = String.valueOf(pe.getCusto());
                tabela[4] = String.valueOf(pe.getValorVenda());
                tabela[5] = String.valueOf(pe.getQtd());
                tabela[6] = pe.getDtEntrada();                                
                tabela[7] = pe.getProdutos().getMarca();
                model.addRow(tabela);
            }
            btCarregarPro.setEnabled(true);
            btCancelarPE.setVisible(true);
        }
    }//GEN-LAST:event_btPesqPActionPerformed

    private void btCarregarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCarregarProActionPerformed
        if (gdPe.getSelectedRow() > -1) {
            edProduto.setText(gdPe.getValueAt(gdPe.getSelectedRow(), 0).toString());
            edCodigo.setText(gdPe.getValueAt(gdPe.getSelectedRow(), 1).toString());
            edDescPro.setText(gdPe.getValueAt(gdPe.getSelectedRow(), 2).toString());                        
            edCusto.setText(gdPe.getValueAt(gdPe.getSelectedRow(), 3).toString());
            edvalVen.setText(gdPe.getValueAt(gdPe.getSelectedRow(),4).toString());
            edQtd.setText(gdPe.getValueAt(gdPe.getSelectedRow(), 5).toString());
            edDt.setText(Formatacao.ajustaDataDMA(gdPe.getValueAt(gdPe.getSelectedRow(), 6).toString()));
            PesqPE.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecione algum produtos da lista.", "Erro",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btCarregarProActionPerformed

    private void btCancelarPEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarPEActionPerformed
        PesqPE.setVisible(false);
    }//GEN-LAST:event_btCancelarPEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProdEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProdEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProdEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProdEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProdEst().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog PesqPE;
    private javax.swing.JDialog PesquisaProdutos;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btCancelarPE;
    private javax.swing.JButton btCarregar;
    private javax.swing.JButton btCarregarPro;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesqP;
    private javax.swing.JButton btPesquProEst;
    private javax.swing.JButton btPesquisa;
    private javax.swing.JButton btPesquisa1;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSalvar;
    private javax.swing.JTextField edCodigo;
    private javax.swing.JFormattedTextField edCusto;
    private javax.swing.JTextField edDescP;
    private javax.swing.JTextField edDescPro;
    private javax.swing.JFormattedTextField edDt;
    private javax.swing.JTextField edProd;
    private javax.swing.JTextField edProduto;
    private javax.swing.JFormattedTextField edQtd;
    private javax.swing.JFormattedTextField edvalVen;
    private javax.swing.JTable gdPe;
    private javax.swing.JTable gdProdutos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_descConta;
    private javax.swing.JLabel label_descConta1;
    // End of variables declaration//GEN-END:variables
}
