/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visoes;

import DAO.FilialDao;
import DAO.UsuarioDao;
import Entidades.Filial;
import Entidades.Usuario;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Murilo
 */
public class CadastroFilial extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFilial
     */
    public CadastroFilial() {
        initComponents();
        gdFilial.getColumnModel().getColumn(4).setMinWidth(0);        
        gdFilial.getColumnModel().getColumn(4).setPreferredWidth(0);
        gdFilial.getColumnModel().getColumn(4).setMaxWidth(0);
    }

    private void limpaTable() {
        DefaultTableModel model = (DefaultTableModel) gdFilial.getModel();
        for (int i = model.getRowCount() - 1; i >= 0; i--) {
            model.removeRow(i);
        }
    }

    private void carregaFilial(Filial filial) {
        edCodigo.setText(filial.getCodigo().toString());
        edNome.setText(filial.getNome());
        edCidade.setText(filial.getCidade());
        edCodigoUsuario.setText(filial.getUsuario().getCodigo().toString());
        edNomeUsuario.setText(filial.getUsuario().getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PesquisaFilial = new javax.swing.JDialog();
        edNome1 = new javax.swing.JTextField();
        btPesquisa1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gdFilial = new javax.swing.JTable();
        btCarregar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        label_descConta = new javax.swing.JLabel();
        PesquisaUsuario = new javax.swing.JDialog();
        edNome2 = new javax.swing.JTextField();
        btPesquisaUsuario = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        gdUsuario = new javax.swing.JTable();
        btCarregar1 = new javax.swing.JButton();
        btCancelar1 = new javax.swing.JButton();
        label_descConta1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edCodigo = new javax.swing.JTextField();
        edNome = new javax.swing.JTextField();
        edCidade = new javax.swing.JTextField();
        btPesquisa = new javax.swing.JButton();
        edNomeUsuario = new javax.swing.JTextField();
        edCodigoUsuario = new javax.swing.JTextField();
        btPesquisa2 = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();

        edNome1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                edNome1FocusLost(evt);
            }
        });
        edNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edNome1ActionPerformed(evt);
            }
        });
        edNome1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edNome1KeyReleased(evt);
            }
        });

        btPesquisa1.setText("Pesquisar");
        btPesquisa1.setMargin(new java.awt.Insets(2, 1, 2, 1));
        btPesquisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisa1ActionPerformed(evt);
            }
        });

        gdFilial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Cidade", "Usuário", "Código"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gdFilial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gdFilialMouseClicked(evt);
            }
        });
        gdFilial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gdFilialKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gdFilialKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(gdFilial);

        btCarregar.setText("Carregar");
        btCarregar.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCarregarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        label_descConta.setText("Nome");

        javax.swing.GroupLayout PesquisaFilialLayout = new javax.swing.GroupLayout(PesquisaFilial.getContentPane());
        PesquisaFilial.getContentPane().setLayout(PesquisaFilialLayout);
        PesquisaFilialLayout.setHorizontalGroup(
            PesquisaFilialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesquisaFilialLayout.createSequentialGroup()
                .addGroup(PesquisaFilialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PesquisaFilialLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PesquisaFilialLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(PesquisaFilialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PesquisaFilialLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE))
                            .addGroup(PesquisaFilialLayout.createSequentialGroup()
                                .addComponent(label_descConta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        PesquisaFilialLayout.setVerticalGroup(
            PesquisaFilialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesquisaFilialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PesquisaFilialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_descConta)
                    .addComponent(edNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisa1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(PesquisaFilialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCarregar)
                    .addComponent(btCancelar))
                .addContainerGap())
        );

        edNome2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                edNome2FocusLost(evt);
            }
        });
        edNome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edNome2ActionPerformed(evt);
            }
        });
        edNome2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edNome2KeyReleased(evt);
            }
        });

        btPesquisaUsuario.setText("Pesquisar");
        btPesquisaUsuario.setMargin(new java.awt.Insets(2, 1, 2, 1));
        btPesquisaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaUsuarioActionPerformed(evt);
            }
        });

        gdUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gdUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gdUsuarioMouseClicked(evt);
            }
        });
        gdUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gdUsuarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gdUsuarioKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(gdUsuario);
        if (gdUsuario.getColumnModel().getColumnCount() > 0) {
            gdUsuario.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        btCarregar1.setText("Carregar");
        btCarregar1.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btCarregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCarregar1ActionPerformed(evt);
            }
        });

        btCancelar1.setText("Cancelar");
        btCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelar1ActionPerformed(evt);
            }
        });

        label_descConta1.setText("Nome");

        javax.swing.GroupLayout PesquisaUsuarioLayout = new javax.swing.GroupLayout(PesquisaUsuario.getContentPane());
        PesquisaUsuario.getContentPane().setLayout(PesquisaUsuarioLayout);
        PesquisaUsuarioLayout.setHorizontalGroup(
            PesquisaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesquisaUsuarioLayout.createSequentialGroup()
                .addGroup(PesquisaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PesquisaUsuarioLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCarregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PesquisaUsuarioLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(label_descConta1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btPesquisaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 93, Short.MAX_VALUE))
                    .addGroup(PesquisaUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PesquisaUsuarioLayout.setVerticalGroup(
            PesquisaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesquisaUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PesquisaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_descConta1)
                    .addComponent(edNome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisaUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PesquisaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCarregar1)
                    .addComponent(btCancelar1))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manutenção de filiais");

        jPanel1.setMinimumSize(new java.awt.Dimension(380, 260));

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Código:");

        jLabel3.setText("Nome:");

        jLabel4.setText("Cidade:");

        jLabel5.setText("Responsável:");

        edCodigo.setEditable(false);
        edCodigo.setName("edCodigo"); // NOI18N
        edCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                edCodigoFocusLost(evt);
            }
        });
        edCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edCodigoActionPerformed(evt);
            }
        });
        edCodigo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                edCodigoPropertyChange(evt);
            }
        });
        edCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edCodigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edCodigoKeyTyped(evt);
            }
        });
        edCodigo.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                edCodigoVetoableChange(evt);
            }
        });

        edNome.setFocusTraversalPolicyProvider(true);
        edNome.setName(""); // NOI18N

        edCidade.setName("edCidade"); // NOI18N

        btPesquisa.setIcon(new javax.swing.ImageIcon("C:\\Users\\Murilo\\Documents\\NetBeansProjects\\ProjetosPAA\\images.png")); // NOI18N
        btPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaActionPerformed(evt);
            }
        });

        edNomeUsuario.setEnabled(false);

        edCodigoUsuario.setEnabled(false);

        btPesquisa2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Murilo\\Documents\\NetBeansProjects\\ProjetosPAA\\images.png")); // NOI18N
        btPesquisa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisa2ActionPerformed(evt);
            }
        });

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(edCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(edNome, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                .addComponent(edCidade))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(edCodigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btPesquisa2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(edCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(edCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(edNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(edCodigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btPesquisa2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(jButton2)
                    .addComponent(btNovo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Filial filial = new Filial();
        Usuario usuario = new Usuario();
        FilialDao filialDao = new FilialDao();
        boolean retorno = false;
        if (edCodigo.getText().equals("")) {            
            filial.setNome(edNome.getText());
            filial.setCidade(edCidade.getText());            
            usuario.setCodigo(Integer.parseInt(edCodigoUsuario.getText()));
            usuario.setNome(edNomeUsuario.getText());
            filial.setUsuario(usuario);
            //filial.setNomeUsuario(edNomeUsuario.getText());

            retorno = filialDao.InsertFilial(filial);
        } else {
            boolean existe = filialDao.existeNoBanco(Integer.parseInt(edCodigo.getText()));
            if (existe) {
                filial.setCodigo(Integer.parseInt(edCodigo.getText()));
                filial.setNome(edNome.getText());
                filial.setCidade(edCidade.getText());
                usuario.setCodigo(Integer.parseInt(edCodigoUsuario.getText()));
                usuario.setNome(edNomeUsuario.getText());
                filial.setUsuario(usuario);                                
                retorno = filialDao.updateFilial(filial);
            }
        }
        if (retorno == true) {
            JOptionPane.showMessageDialog(null, "Gravado com sucesso!");                        
            carregaFilial(filial);            
        } else {
            JOptionPane.showMessageDialog(null, "Erro!");
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void edCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edCodigoFocusLost
        /*        ClienteDao clienteDao = new ClienteDao();
         List<Cliente> list = new ArrayList();
         if (edCodigo.equals("")) {
         limpaTela();
         } else {

         Cliente cliente = new Cliente();
         try {
         //                list = clienteDao.procuraPorCodigo(Integer.parseInt(edCodigo.getText()));
         //for (Cliente cliente : list) {
         //                    edCodigo.setText(cliente.getCodigo().toString());

         //                }

         } catch (Exception ex) {
         Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
         }
         if (cliente == null) {
         limpaTela();
         } else {
         //carregaPaci(paciente);
         }
         }*/
    }//GEN-LAST:event_edCodigoFocusLost

    private void edCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edCodigoActionPerformed

    private void edCodigoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_edCodigoPropertyChange

    }//GEN-LAST:event_edCodigoPropertyChange

    private void edCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edCodigoKeyReleased

    }//GEN-LAST:event_edCodigoKeyReleased

    private void edCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edCodigoKeyTyped

    }//GEN-LAST:event_edCodigoKeyTyped

    private void edCodigoVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_edCodigoVetoableChange

    }//GEN-LAST:event_edCodigoVetoableChange

    private void btPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaActionPerformed
        //        ConsultaCliente pesqCli = new ConsultaCliente();
        //        Cliente cliente = new Cliente();
        //        pesqCli.setCliente(cliente);
        //        pesqCli.setVisible(true);
        //        carregaCliente(cliente);
        PesquisaFilial.setSize(600, 450);
        PesquisaFilial.setModal(true);
        PesquisaFilial.setLocation(200, 100);
        PesquisaFilial.setVisible(true);
    }//GEN-LAST:event_btPesquisaActionPerformed

    private void edNome1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edNome1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_edNome1FocusLost

    private void edNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edNome1ActionPerformed

    private void edNome1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edNome1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_edNome1KeyReleased

    private void btPesquisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisa1ActionPerformed
        limpaTable();
        DefaultTableModel model = (DefaultTableModel) gdFilial.getModel();
        FilialDao filialDao = new FilialDao();
        List<Filial> list = new ArrayList();

        if (edNome.getText().equals("")) {
            try {
                list = filialDao.pesqView();
            } catch (Exception ex) {
                Logger.getLogger(PesquisaFilial.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                list = filialDao.pesquisaFilial(edNome.getText());
            } catch (Exception ex) {
                Logger.getLogger(PesquisaFilial.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if (list.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Filial não localizada.", "Erro",
                    JOptionPane.ERROR_MESSAGE);
            btCarregar.setEnabled(false);
        } else {
            String tabela[] = new String[]{"", "", "", "",""};
            for (Filial filial : list) {
                tabela[0] = String.valueOf(filial.getCodigo());
                tabela[1] = filial.getNome();
                tabela[2] = filial.getCidade();
                tabela[3] = filial.getUsuario().getNome();
                tabela[4] = String.valueOf(filial.getUsuario().getCodigo());                

                model.addRow(tabela);
            }
            btCarregar.setEnabled(true);
            gdFilial.setVisible(true);
        }
    }//GEN-LAST:event_btPesquisa1ActionPerformed

    private void gdFilialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gdFilialMouseClicked
        if (evt.getClickCount() == 2) {
            if (gdFilial.getSelectedRow() > -1) {
                edCodigo.setText(gdFilial.getValueAt(gdFilial.getSelectedRow(), 0).toString());
                edNome.setText(gdFilial.getValueAt(gdFilial.getSelectedRow(), 1).toString());
                edCidade.setText(gdFilial.getValueAt(gdFilial.getSelectedRow(), 2).toString());
                edNomeUsuario.setText(gdFilial.getValueAt(gdFilial.getSelectedRow(), 3).toString());
                edCodigoUsuario.setText(gdFilial.getValueAt(gdFilial.getSelectedRow(),4).toString());
                PesquisaFilial.setVisible(false);
            }
        }
    }//GEN-LAST:event_gdFilialMouseClicked

    private void gdFilialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gdFilialKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_gdFilialKeyReleased

    private void gdFilialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gdFilialKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_gdFilialKeyTyped

    private void btCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCarregarActionPerformed
        //DefaultTableModel model = (DefaultTableModel) gdClientes.getModel();
        if (gdFilial.getSelectedRow() > -1) {
            edCodigo.setText(gdFilial.getValueAt(gdFilial.getSelectedRow(), 0).toString());
            edNome.setText(gdFilial.getValueAt(gdFilial.getSelectedRow(), 1).toString());
            edCidade.setText(gdFilial.getValueAt(gdFilial.getSelectedRow(), 2).toString());
            edNomeUsuario.setText(gdFilial.getValueAt(gdFilial.getSelectedRow(), 3).toString());
            edCodigoUsuario.setText(gdFilial.getValueAt(gdFilial.getSelectedRow(),4).toString());
            PesquisaFilial.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecione alguma filial da lista.", "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btCarregarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        PesquisaFilial.setVisible(false);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btPesquisa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisa2ActionPerformed
        PesquisaUsuario.setSize(400, 400);
        PesquisaUsuario.setModal(true);
        PesquisaUsuario.setLocation(200, 100);
        PesquisaUsuario.setVisible(true);
    }//GEN-LAST:event_btPesquisa2ActionPerformed

    private void edNome2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edNome2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_edNome2FocusLost

    private void edNome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edNome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edNome2ActionPerformed

    private void edNome2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edNome2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_edNome2KeyReleased

    private void btPesquisaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaUsuarioActionPerformed
        limpaTable();
        DefaultTableModel model = (DefaultTableModel) gdUsuario.getModel();
        UsuarioDao usuarioDao = new UsuarioDao();
        List<Usuario> list = new ArrayList();

        if (edNome2.getText().equals("")) {
            try {
                list = usuarioDao.encontrarTudo();
            } catch (Exception ex) {
                Logger.getLogger(PesquisaUsuario.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                list = usuarioDao.pesquisaUsuario(edNome2.getText());
            } catch (Exception ex) {
                Logger.getLogger(PesquisaUsuario.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if (list.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Usuário não localizado.", "Erro",
                    JOptionPane.ERROR_MESSAGE);
            btCarregar.setEnabled(false);
        } else {
            String tabela[] = new String[]{"", ""};
            for (Usuario usuario : list) {
                tabela[0] = String.valueOf(usuario.getCodigo());
                tabela[1] = usuario.getNome();

                model.addRow(tabela);
            }
            btCarregar.setEnabled(true);
            gdUsuario.setVisible(true);
        }
    }//GEN-LAST:event_btPesquisaUsuarioActionPerformed

    private void gdUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gdUsuarioMouseClicked
        if (evt.getClickCount() == 2) {
            if (gdUsuario.getSelectedRow() > -1) {
                edCodigoUsuario.setText(gdUsuario.getValueAt(gdUsuario.getSelectedRow(), 0).toString());
                edNomeUsuario.setText(gdUsuario.getValueAt(gdUsuario.getSelectedRow(), 1).toString());
                PesquisaUsuario.setVisible(false);
            }
        }
    }//GEN-LAST:event_gdUsuarioMouseClicked

    private void gdUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gdUsuarioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_gdUsuarioKeyReleased

    private void gdUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gdUsuarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_gdUsuarioKeyTyped

    private void btCarregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCarregar1ActionPerformed
        //DefaultTableModel model = (DefaultTableModel) gdClientes.getModel();
        if (gdUsuario.getSelectedRow() > -1) {
            edCodigoUsuario.setText(gdUsuario.getValueAt(gdUsuario.getSelectedRow(), 0).toString());
            edNomeUsuario.setText(gdUsuario.getValueAt(gdUsuario.getSelectedRow(), 1).toString());
            PesquisaUsuario.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecione algum usuário da lista.", "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btCarregar1ActionPerformed

    private void btCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelar1ActionPerformed
        PesquisaUsuario.setVisible(false);
    }//GEN-LAST:event_btCancelar1ActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        edCodigo.setText("");
        edNome.setText("");
        edCidade.setText("");
        edCodigoUsuario.setText("");
        edNomeUsuario.setText("");
        edNome.grabFocus();
    }//GEN-LAST:event_btNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFilial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFilial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFilial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFilial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFilial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog PesquisaFilial;
    private javax.swing.JDialog PesquisaUsuario;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btCancelar1;
    private javax.swing.JButton btCarregar;
    private javax.swing.JButton btCarregar1;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisa;
    private javax.swing.JButton btPesquisa1;
    private javax.swing.JButton btPesquisa2;
    private javax.swing.JButton btPesquisaUsuario;
    private javax.swing.JButton btSalvar;
    private javax.swing.JTextField edCidade;
    private javax.swing.JTextField edCodigo;
    private javax.swing.JTextField edCodigoUsuario;
    private javax.swing.JTextField edNome;
    private javax.swing.JTextField edNome1;
    private javax.swing.JTextField edNome2;
    private javax.swing.JTextField edNomeUsuario;
    private javax.swing.JTable gdFilial;
    private javax.swing.JTable gdUsuario;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_descConta;
    private javax.swing.JLabel label_descConta1;
    // End of variables declaration//GEN-END:variables
}
