package Entidades;
// Generated 04/11/2015 21:22:04 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Auditoria generated by hbm2java
 */
public class Auditoria  implements java.io.Serializable {


     private Integer codigo;
     private Usuario usuario;
     private Date dataHora;
     private String acao;
     private String valorAnterior;
     private String valorPosterior;

    public Auditoria() {
    }

	
    public Auditoria(Usuario usuario) {
        this.usuario = usuario;
    }
    public Auditoria(Usuario usuario, Date dataHora, String acao, String valorAnterior, String valorPosterior) {
       this.usuario = usuario;
       this.dataHora = dataHora;
       this.acao = acao;
       this.valorAnterior = valorAnterior;
       this.valorPosterior = valorPosterior;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getDataHora() {
        return this.dataHora;
    }
    
    public void setDataHora(Date dataHora) {
        this.dataHora = dataHora;
    }
    public String getAcao() {
        return this.acao;
    }
    
    public void setAcao(String acao) {
        this.acao = acao;
    }
    public String getValorAnterior() {
        return this.valorAnterior;
    }
    
    public void setValorAnterior(String valorAnterior) {
        this.valorAnterior = valorAnterior;
    }
    public String getValorPosterior() {
        return this.valorPosterior;
    }
    
    public void setValorPosterior(String valorPosterior) {
        this.valorPosterior = valorPosterior;
    }




}


