package Entidades;
// Generated 12/10/2015 12:43:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer codigo;
     private String nome;
     private String telefone;
     private String ceuluar;
     private String email;
     private Set orcamentos = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String nome) {
        this.nome = nome;
    }
    public Cliente(String nome, String telefone, String ceuluar, String email, Set orcamentos) {
       this.nome = nome;
       this.telefone = telefone;
       this.ceuluar = ceuluar;
       this.email = email;
       this.orcamentos = orcamentos;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getCeuluar() {
        return this.ceuluar;
    }
    
    public void setCeuluar(String ceuluar) {
        this.ceuluar = ceuluar;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getOrcamentos() {
        return this.orcamentos;
    }
    
    public void setOrcamentos(Set orcamentos) {
        this.orcamentos = orcamentos;
    }




}


