package Entidades;
// Generated 04/11/2015 21:22:04 by Hibernate Tools 4.3.1



/**
 * Estoque generated by hbm2java
 */
public class Estoque  implements java.io.Serializable {


     private int produto;
     private Integer qtd;

    public Estoque() {
    }

	
    public Estoque(int produto) {
        this.produto = produto;
    }
    public Estoque(int produto, Integer qtd) {
       this.produto = produto;
       this.qtd = qtd;
    }
   
    public int getProduto() {
        return this.produto;
    }
    
    public void setProduto(int produto) {
        this.produto = produto;
    }
    public Integer getQtd() {
        return this.qtd;
    }
    
    public void setQtd(Integer qtd) {
        this.qtd = qtd;
    }




}


