package Entidades;
// Generated 04/11/2015 21:22:04 by Hibernate Tools 4.3.1



/**
 * Filial generated by hbm2java
 */
public class Filial  implements java.io.Serializable {


     private Integer codigo;
     private Usuario usuario;
     private String nome;
     private String cidade;

    public Filial() {
    }

    public Filial(Usuario usuario, String nome, String cidade) {
       this.usuario = usuario;
       this.nome = nome;
       this.cidade = cidade;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }




}


