package Entidades;
// Generated 25/08/2015 19:46:47 by Hibernate Tools 4.3.1



/**
 * Filial generated by hbm2java
 */
public class Filial  implements java.io.Serializable {


     private Integer codigo;
     private int usuario;
     private String nome;
     private String cidade;
     private String nomeUsuario;

    public String getNomeUsuario() {
        return nomeUsuario;
    }

    public void setNomeUsuario(String nomeUsuario) {
        this.nomeUsuario = nomeUsuario;
    }

    public Filial() {
    }

    public Filial(int usuario, String nome, String cidade) {
       this.usuario = usuario;
       this.nome = nome;
       this.cidade = cidade;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public int getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(int usuario) {
        this.usuario = usuario;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }




}


