package Entidades;
// Generated 25/08/2015 19:25:23 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orcamento generated by hbm2java
 */
public class Orcamento  implements java.io.Serializable {


     private Integer codigo;
     private Cliente cliente;
     private Date data;
     private Set orcamentoProdutoestoques = new HashSet(0);

    public Orcamento() {
    }

	
    public Orcamento(Cliente cliente) {
        this.cliente = cliente;
    }
    public Orcamento(Cliente cliente, Date data, Set orcamentoProdutoestoques) {
       this.cliente = cliente;
       this.data = data;
       this.orcamentoProdutoestoques = orcamentoProdutoestoques;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Set getOrcamentoProdutoestoques() {
        return this.orcamentoProdutoestoques;
    }
    
    public void setOrcamentoProdutoestoques(Set orcamentoProdutoestoques) {
        this.orcamentoProdutoestoques = orcamentoProdutoestoques;
    }




}


