package Entidades;
// Generated 12/10/2015 12:43:43 by Hibernate Tools 4.3.1



/**
 * OrcamentoProdutoestoque generated by hbm2java
 */
public class OrcamentoProdutoestoque  implements java.io.Serializable {


     private OrcamentoProdutoestoqueId id;
     private Orcamento orcamento;
     private Produtoestoque produtoestoque;

    public OrcamentoProdutoestoque() {
    }

    public OrcamentoProdutoestoque(OrcamentoProdutoestoqueId id, Orcamento orcamento, Produtoestoque produtoestoque) {
       this.id = id;
       this.orcamento = orcamento;
       this.produtoestoque = produtoestoque;
    }
   
    public OrcamentoProdutoestoqueId getId() {
        return this.id;
    }
    
    public void setId(OrcamentoProdutoestoqueId id) {
        this.id = id;
    }
    public Orcamento getOrcamento() {
        return this.orcamento;
    }
    
    public void setOrcamento(Orcamento orcamento) {
        this.orcamento = orcamento;
    }
    public Produtoestoque getProdutoestoque() {
        return this.produtoestoque;
    }
    
    public void setProdutoestoque(Produtoestoque produtoestoque) {
        this.produtoestoque = produtoestoque;
    }




}


