package Entidades;
// Generated 04/11/2015 21:22:04 by Hibernate Tools 4.3.1



/**
 * OrcamentoProdutoestoque generated by hbm2java
 */
public class OrcamentoProdutoestoque  implements java.io.Serializable {


     private OrcamentoProdutoestoqueId id;
     private Orcamento orcamento;
     private Produtoestoque produtoestoque;
     private int qtd;

    public OrcamentoProdutoestoque() {
    }

    public OrcamentoProdutoestoque(OrcamentoProdutoestoqueId id, Orcamento orcamento, Produtoestoque produtoestoque, int qtd) {
       this.id = id;
       this.orcamento = orcamento;
       this.produtoestoque = produtoestoque;
       this.qtd = qtd;
    }
   
    public OrcamentoProdutoestoqueId getId() {
        return this.id;
    }
    
    public void setId(OrcamentoProdutoestoqueId id) {
        this.id = id;
    }
    public Orcamento getOrcamento() {
        return this.orcamento;
    }
    
    public void setOrcamento(Orcamento orcamento) {
        this.orcamento = orcamento;
    }
    public Produtoestoque getProdutoestoque() {
        return this.produtoestoque;
    }
    
    public void setProdutoestoque(Produtoestoque produtoestoque) {
        this.produtoestoque = produtoestoque;
    }
    public int getQtd() {
        return this.qtd;
    }
    
    public void setQtd(int qtd) {
        this.qtd = qtd;
    }




}


