package Entidades;
// Generated 25/08/2015 19:46:47 by Hibernate Tools 4.3.1



/**
 * OrcamentoProdutoestoqueId generated by hbm2java
 */
public class OrcamentoProdutoestoqueId  implements java.io.Serializable {


     private int produtoEstoqueProdutosCodigo;
     private int produtoEstoqueCodigoEstoque;
     private int orcamentoCodigo;

    public OrcamentoProdutoestoqueId() {
    }

    public OrcamentoProdutoestoqueId(int produtoEstoqueProdutosCodigo, int produtoEstoqueCodigoEstoque, int orcamentoCodigo) {
       this.produtoEstoqueProdutosCodigo = produtoEstoqueProdutosCodigo;
       this.produtoEstoqueCodigoEstoque = produtoEstoqueCodigoEstoque;
       this.orcamentoCodigo = orcamentoCodigo;
    }
   
    public int getProdutoEstoqueProdutosCodigo() {
        return this.produtoEstoqueProdutosCodigo;
    }
    
    public void setProdutoEstoqueProdutosCodigo(int produtoEstoqueProdutosCodigo) {
        this.produtoEstoqueProdutosCodigo = produtoEstoqueProdutosCodigo;
    }
    public int getProdutoEstoqueCodigoEstoque() {
        return this.produtoEstoqueCodigoEstoque;
    }
    
    public void setProdutoEstoqueCodigoEstoque(int produtoEstoqueCodigoEstoque) {
        this.produtoEstoqueCodigoEstoque = produtoEstoqueCodigoEstoque;
    }
    public int getOrcamentoCodigo() {
        return this.orcamentoCodigo;
    }
    
    public void setOrcamentoCodigo(int orcamentoCodigo) {
        this.orcamentoCodigo = orcamentoCodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrcamentoProdutoestoqueId) ) return false;
		 OrcamentoProdutoestoqueId castOther = ( OrcamentoProdutoestoqueId ) other; 
         
		 return (this.getProdutoEstoqueProdutosCodigo()==castOther.getProdutoEstoqueProdutosCodigo())
 && (this.getProdutoEstoqueCodigoEstoque()==castOther.getProdutoEstoqueCodigoEstoque())
 && (this.getOrcamentoCodigo()==castOther.getOrcamentoCodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProdutoEstoqueProdutosCodigo();
         result = 37 * result + this.getProdutoEstoqueCodigoEstoque();
         result = 37 * result + this.getOrcamentoCodigo();
         return result;
   }   


}


