package Entidades;
// Generated 25/08/2015 19:46:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Produtos generated by hbm2java
 */
public class Produtos  implements java.io.Serializable {


     private Integer codigo;
     private String descricao;
     private String marca;

    public String getMarca() {
        return marca;
    }

    public void setMarca(String marca) {
        this.marca = marca;
    }
     private Set produtoestoques = new HashSet(0);

    public Produtos() {
    }

	
    public Produtos(String descricao) {
        this.descricao = descricao;
    }

    public Produtos(Integer codigo, String descricao, String marca) {
        this.codigo = codigo;
        this.descricao = descricao;
        this.marca = marca;
    }
    
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getProdutoestoques() {
        return this.produtoestoques;
    }
    
    public void setProdutoestoques(Set produtoestoques) {
        this.produtoestoques = produtoestoques;
    }




}


