package Entidades;
// Generated 12/10/2015 12:43:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Produtos generated by hbm2java
 */
public class Produtos  implements java.io.Serializable {


     private Integer codigo;
     private String descricao;
     private String marca;
     private Set produtoestoques = new HashSet(0);

    public Produtos() {
    }

	
    public Produtos(String descricao, String marca) {
        this.descricao = descricao;
        this.marca = marca;
    }
    public Produtos(String descricao, String marca, Set produtoestoques) {
       this.descricao = descricao;
       this.marca = marca;
       this.produtoestoques = produtoestoques;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public Set getProdutoestoques() {
        return this.produtoestoques;
    }
    
    public void setProdutoestoques(Set produtoestoques) {
        this.produtoestoques = produtoestoques;
    }




}


